### ISSUE TITLE
Service Account for GCP Setup

### ISSUE THREAD

**Issue by mik-laj** [PolideaInternal/airflow-system-tests#6]
Hello,

We should manage the accounts and accesses in a transparent manner, portable between projects and user-friendly.  

For this purpose, we can use Terraform,
- It will be easy to run, to configure all the accesses required for the accounts. 
- Thanks to the parameterization of the plan, it will also be portable between projects.
- The creation of all accounts will also be user-friendly, as terraform only requires one command to be executed to create even a complex infrastructure.

**Tasks:**

- [ ] Create a service account
- [ ] Create IAM policy
- [ ] Setup KMS
- [ ] Generate service account key file and upload encrypted key file to GCS/Source Repository
